---
title: "Phoenix Sepsis EHR Implementation Notes"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


D_dimer mg/l feu <= 500
GCS Total - gcs_total >= 3 and <= 15 (i.e. GCS should be between 3 and 15)
Lactate mmol/l <= 50
DBP - DBP >= 1 and DBP <= 200
SBP - SBP >= 1 and SBP <= 300
MAP (mean arterial pressure) - MAP >= 1 and MAP <= 300
Glucose - Glucose mg/dl >= 5 and Glucose mg/dl <= 2000

# General notes

* `NULL` values are treated as non-score generating criteria. Do not populate null/unknown/not applicable values with estimates or outdated information.
* Values outside ranges mentioned below are treated as `NULL`
* Before sending data to the package, verify data. Some values may provide warnings, others may throw errors. Verify your processing can handle warnings and errors.

# Respiratory

Provide **one** of the following for the Respiratory score:

* PaO~2~ to FiO~2~ ratio
* SpO~2~ to FiO~2~ ratio
* PaO~2~ and FiO~2~
* SpO~2~ and FiO~2~

If multiple options are available, select the first one available based on order above.

## FiO~2~

Float value with range from 0.21 to 1.00

## PaO~2~

Float value greater than 0

## SpO~2~

Integer value with range from 0 to 100; > 97% should not be used for S/F ratio. If SpO~2~ and FiO~2~ is passed, package will discard values if SpO~2~ is >= 97%.

## Respiratory Support

* The respiratory dysfunction of 1 point can be assessed in any patient receiving oxygen support of any kind, including high-flow, noninvasive positive pressure, or invasive mechanical ventalation (IMV) respiratory support.
* The respiratory dysfunction of 2 point can only be assessed in the presence of invasive mechanical ventalation (IMV) respiratory support.

# Cardiovascular

## Systemic Vasoactive Medications

Vasoactive medications (dobutamine, dopamine, etc.) should only count if they are systemic. In our older dataset, epinephrine had some non-systemic medication administrations. e.g. "epinephrine hcl 2.25 % inh neb soln" should not count towards the systemic vasoactive medication count towards cardiovascular system disfunction points. The Phoenix python package documentation does mention this requirement, but the package doesn't enforce it.

## Lactate

## Age
## Blood Pressure


for BP, prefer arterial over cuff...

# Coagulation

## Platelets
## INR
## D-dimer
## Fibrinogen

# Neurologic
## GCS

Package only allows for GCS total. GCS should be an integer in the range: 3 - 15

If GCS total is not available, it can be calculated from the subcomponents `eye + motor + verbal`

* GCS Eye range: 1 - 4
* GCS Motor range: 1 - 6
* GCS Verbal range: 1 - 5

## Pupils

# Endocrine
## Glucose

# Immunologic
## ANC
## ALC

# Renal
## Age (see notes in cardiovascular)
## Creatinine

# Hepatic

## Total Bilirubin

Units should be in mg/dL, or converted to mg/dL and range from 0 - 100.

## ALT

