// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// phoenixRespiratory
arma::vec phoenixRespiratory(arma::vec pfRatio, arma::vec sfRatio, arma::vec imv, arma::vec respSupport);
RcppExport SEXP _phoenix_phoenixRespiratory(SEXP pfRatioSEXP, SEXP sfRatioSEXP, SEXP imvSEXP, SEXP respSupportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pfRatio(pfRatioSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type sfRatio(sfRatioSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type imv(imvSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type respSupport(respSupportSEXP);
    rcpp_result_gen = Rcpp::wrap(phoenixRespiratory(pfRatio, sfRatio, imv, respSupport));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_phoenix_phoenixRespiratory", (DL_FUNC) &_phoenix_phoenixRespiratory, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_phoenix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
